### ISSUE TITLE
Mock数据的几点疑问

### ISSUE THREAD

**Issue by SoyMeng** [sx1989827/SBDoc#1]
1. 如果返回结果是一个Array,是否可以生成固定数量的数据？当前只能生成一条数据。
2. mixed是在应用在什么类型的数据上？

**Comment by sx1989827** [comment]
1.这个需求我会好好考虑下加进去的，支持生成固定数量的数据
2.mixed应用于那些类型不固定的字段，例如{"type":1,"data":[]}  {"type":2,"data":{}},对于上面两个json，data的类型会根据type的类型而定

非常感谢你提的几个建议，我都认真看了下，也非常感谢你对产品的支持，我会越做越好的~
