### ISSUE TITLE
post json参数类型

### ISSUE THREAD

**Issue by SoyMeng** [sx1989827/SBDoc#2]
POST|PUT 类型为JSON时可编辑参数。现在只在Raw中

**Comment by sx1989827** [comment]
你好，get没有http body，会在什么情况下传json呢，是在query里面吗？

**Comment by SoyMeng** [comment]
嗯，应该是POST|PUT。

POST提交一个JSON格式的内容

当前只能使用：
![image](https://cloud.githubusercontent.com/assets/6083582/23979040/0b516fa0-0a32-11e7-9653-ab5917a78159.png)

**Comment by cysnake4713** [comment]
同问,这块的UI要是能改改就更好了,想问一下如果要改是哪个文件?

**Comment by sx1989827** [comment]
你好，这一块我们会在下一版本进行优化，添加相关的功能的~

**Comment by sx1989827** [comment]
目前已支持json格式的入参
