### ISSUE TITLE
支持导入postman编写的接口

### ISSUE THREAD

**Issue by is00hcw** [sx1989827/SBDoc#5]
postman是一个很常用的接口测试工具，它可以生成各种语言的测试代码，或者自动化测试HTTP接口。postman可以把接口定义导出为JSON文件，希望本项目能够支持导入这种接口定义的JSON文件，这样就可以很方面的在SBDoc修改，添加描述、备注，生成文档了。

**Comment by sx1989827** [comment]
好的 这个功能会在下一版本实现

**Comment by sx1989827** [comment]
目前已支持postman v2文档的导入
