### ISSUE TITLE
请问有文档导出功能吗?

### ISSUE THREAD

**Issue by SwenChan** [sx1989827/SBDoc#6]
rt.
另外，界面真好看。考虑打成docker包吗，我来打个包吧

**Comment by sx1989827** [comment]
目前还没有啊，下一个版本会推出，支持你打个docker包哈~

**Comment by hodgevk** [comment]
@SwenChan docker包弄了吗？

**Comment by sx1989827** [comment]
目前已经添加导入导出功能，下一版本会添加导出到html打包文件的功能
